use std::sync::Arc;

use crate::common::{
    auth::{claims::Claims, jwt::generate_jwt},
    error::AppError,
    security::{validate_password, AccountLockoutService, LockoutConfig},
};
use uuid::Uuid;

use super::{
    model::{hash_password, verify_password, LoginRequest, LoginResponse, UserProfile},
    repo::{find_user_by_username, get_user_permissions, get_user_roles},
};

// Settings is imported from config module
use crate::config::Settings;

/// Info needed to create an online user record
#[derive(Debug)]
pub struct OnlineUserInfo {
    pub session_id: String,
    pub user_id: Uuid,
    pub username: String,
    pub ip_address: String,
    pub browser: String,
    pub os: String,
}

pub struct AuthService {
    config: Arc<Settings>,
    lockout_service: AccountLockoutService,
}

impl AuthService {
    pub fn new(config: Arc<Settings>) -> Self {
        Self {
            config,
            lockout_service: AccountLockoutService::new(LockoutConfig::default()),
        }
    }

    pub async fn login(&self, db: &sqlx::PgPool, req: LoginRequest) -> Result<LoginResponse, AppError> {
        // Check if account is locked before authentication
        match self.lockout_service.is_locked(db, &req.username).await {
            Ok(true) => {
                let status = self.lockout_service.get_lockout_status(db, &req.username)
                    .await
                    .map_err(|e| AppError::Internal(Some(format!("Lockout service error: {}", e))))?;
                let retry_after = status.locked_until
                    .map(|locked| (locked - chrono::Utc::now()).num_seconds().max(0) as u64)
                    .unwrap_or(900); // Default 15 minutes
                return Err(AppError::Authentication(format!(
                    "Account is locked. Please try again in {} seconds",
                    retry_after
                )));
            }
            Ok(false) => {}
            Err(e) => {
                tracing::warn!("Failed to check lockout status: {}", e);
            }
        }

        // Find user by username
        let user = find_user_by_username(db, &req.username)
            .await?
            .ok_or_else(|| AppError::Authentication("Invalid username or password".to_string()))?;

        // Verify password
        let is_valid = verify_password(&req.password, &user.password_hash)?;
        if !is_valid {
            // Record failed attempt
            if let Err(e) = self.lockout_service.record_failed_attempt(db, &req.username).await {
                tracing::warn!("Failed to record failed login attempt: {}", e);
            }
            return Err(AppError::Authentication("Invalid username or password".to_string()));
        }

        // Reset failed attempts on successful login
        if let Err(e) = self.lockout_service.reset_attempts(db, &req.username).await {
            tracing::warn!("Failed to reset login attempts: {}", e);
        }

        // Get user permissions and roles
        let permissions = get_user_permissions(db, user.id).await?;
        let roles = get_user_roles(db, user.id).await?;

        // Create JWT claims (clone for claims since they consume the values)
        let claims = Claims::new(
            user.id,
            user.username.clone(),
            permissions.clone(),
            user.dept_id,
            roles.clone(),
        );

        // Generate JWT token
        let token = generate_jwt(claims, &self.config.jwt.secret)?;

        Ok(LoginResponse {
            token,
            session_id: None, // Session ID is generated by the route handler after login
            userInfo: UserProfile {
                id: user.id,
                username: user.username,
                display_name: user.display_name,
                email: user.email,
                dept_id: user.dept_id,
                avatar_url: user.avatar_url,
                permissions,
                roles,
            },
        })
    }

    /// Create an online user record in sys_online_user table
    pub async fn create_online_user(
        &self,
        db: &sqlx::PgPool,
        info: OnlineUserInfo,
    ) -> Result<(), AppError> {
        sqlx::query(
            r#"
            INSERT INTO sys_online_user (
                session_id, user_id, username, ip_address, browser, os,
                login_time, last_access_time, expire_time
            ) VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW(), NOW() + INTERVAL '24 hours')
            ON CONFLICT (session_id) DO UPDATE SET
                last_access_time = NOW(),
                ip_address = EXCLUDED.ip_address,
                expire_time = NOW() + INTERVAL '24 hours'
            "#,
        )
        .bind(&info.session_id)
        .bind(info.user_id)
        .bind(&info.username)
        .bind(&info.ip_address)
        .bind(&info.browser)
        .bind(&info.os)
        .execute(db)
        .await
        .map_err(|e| AppError::Internal(Some(format!("Failed to create online user record: {}", e))))?;

        tracing::info!(
            "Created online user record for user {} (session: {})",
            info.username,
            info.session_id
        );

        Ok(())
    }

    /// Delete an online user record by session_id
    pub async fn delete_online_user_by_session(
        &self,
        db: &sqlx::PgPool,
        session_id: &str,
    ) -> Result<(), AppError> {
        let result = sqlx::query(
            r#"DELETE FROM sys_online_user WHERE session_id = $1"#,
        )
        .bind(session_id)
        .execute(db)
        .await
        .map_err(|e| AppError::Internal(Some(format!("Failed to delete online user record: {}", e))))?;

        if result.rows_affected() > 0 {
            tracing::info!("Deleted online user record for session: {}", session_id);
        }

        Ok(())
    }

    /// Delete an online user record by user_id (for logout when session_id not available)
    pub async fn delete_online_user_by_user(
        &self,
        db: &sqlx::PgPool,
        user_id: Uuid,
    ) -> Result<(), AppError> {
        let result = sqlx::query(
            r#"DELETE FROM sys_online_user WHERE user_id = $1"#,
        )
        .bind(user_id)
        .execute(db)
        .await
        .map_err(|e| AppError::Internal(Some(format!("Failed to delete online user record: {}", e))))?;

        if result.rows_affected() > 0 {
            tracing::info!("Deleted online user record for user: {}", user_id);
        }

        Ok(())
    }

    /// Delete all online user records for a user (all sessions)
    pub async fn delete_all_online_users_for_user(
        &self,
        db: &sqlx::PgPool,
        user_id: Uuid,
    ) -> Result<u64, AppError> {
        let result = sqlx::query(
            r#"DELETE FROM sys_online_user WHERE user_id = $1"#,
        )
        .bind(user_id)
        .execute(db)
        .await
        .map_err(|e| AppError::Internal(Some(format!("Failed to delete online user records: {}", e))))?;

        let count = result.rows_affected();
        if count > 0 {
            tracing::info!("Deleted {} online user record(s) for user: {}", count, user_id);
        }

        Ok(count)
    }

    /// Clean up expired online user sessions
    /// Deletes all records where expire_time < NOW()
    /// Returns the number of deleted records
    pub async fn cleanup_expired_sessions(
        &self,
        db: &sqlx::PgPool,
    ) -> Result<u64, AppError> {
        let result = sqlx::query(
            r#"DELETE FROM sys_online_user WHERE expire_time < NOW()"#,
        )
        .execute(db)
        .await
        .map_err(|e| AppError::Internal(Some(format!("Failed to cleanup expired sessions: {}", e))))?;

        let count = result.rows_affected();
        if count > 0 {
            tracing::info!("Cleaned up {} expired online user session(s)", count);
        }

        Ok(count)
    }

    /// Get count of active online users
    pub async fn get_online_user_count(
        &self,
        db: &sqlx::PgPool,
    ) -> Result<i64, AppError> {
        let result = sqlx::query_scalar::<_, i64>(
            r#"SELECT COUNT(*) FROM sys_online_user WHERE expire_time >= NOW()"#,
        )
        .fetch_one(db)
        .await
        .map_err(|e| AppError::Internal(Some(format!("Failed to get online user count: {}", e))))?;

        Ok(result)
    }

    pub async fn register(
        &self,
        db: &sqlx::PgPool,
        username: String,
        password: String,
        email: Option<String>,
        display_name: String,
    ) -> Result<(), AppError> {
        // Validate password
        let policy = crate::common::security::PasswordPolicy::default();
        validate_password(&password, &policy)
            .map_err(|_| AppError::Validation { field: "password".to_string(), message: "Password does not meet complexity requirements".to_string() })?;

        // Check username is not in password
        if password.to_lowercase().contains(&username.to_lowercase()) {
            return Err(AppError::Validation { field: "password".to_string(), message: "Password must not contain username".to_string() });
        }

        // Hash password
        let password_hash = hash_password(&password)?;

        // Create user in database
        let _ = sqlx::query(
            r#"
            INSERT INTO sys_users (username, password_hash, email, display_name, status, created_at)
            VALUES ($1, $2, $3, $4, 'ACTIVE', NOW())
            "#,
        )
        .bind(&username)
        .bind(&password_hash)
        .bind(&email)
        .bind(&display_name)
        .execute(db)
        .await
        .map_err(|e| AppError::Internal(Some(format!("Failed to create user: {}", e))))?;

        Ok(())
    }

    pub async fn get_current_user_profile(
        &self,
        db: &sqlx::PgPool,
        user_id: Uuid,
    ) -> Result<UserProfile, AppError> {
        // Get user details
        let user = sqlx::query_as::<_, (Uuid, String, String, Option<String>, Option<Uuid>, Option<String>)>(
            r#"
            SELECT
                id,
                username,
                display_name,
                email,
                dept_id,
                avatar_url
            FROM sys_users
            WHERE id = $1
            "#,
        )
        .bind(user_id)
        .fetch_one(db)
        .await
        .map_err(|_| AppError::Authentication("User not found".to_string()))?;

        // Get user permissions and roles
        let permissions = get_user_permissions(db, user_id).await?;
        let roles = get_user_roles(db, user_id).await?;

        Ok(UserProfile {
            id: user.0,
            username: user.1,
            display_name: user.2,
            email: user.3,
            dept_id: user.4,
            avatar_url: user.5,
            permissions,
            roles,
        })
    }

    pub async fn change_password(
        &self,
        db: &sqlx::PgPool,
        user_id: Uuid,
        old_password: String,
        new_password: String,
    ) -> Result<(), AppError> {
        // Validate new password
        let policy = crate::common::security::PasswordPolicy::default();
        validate_password(&new_password, &policy)
            .map_err(|_| AppError::Validation { field: "new_password".to_string(), message: "New password does not meet complexity requirements".to_string() })?;

        // Get user
        let user = sqlx::query_as::<_, (Uuid, String, String)>(
            r#"
            SELECT id, username, password_hash
            FROM sys_users
            WHERE id = $1
            "#,
        )
        .bind(user_id)
        .fetch_one(db)
        .await
        .map_err(|_| AppError::Authentication("User not found".to_string()))?;

        // Verify old password
        let is_valid = verify_password(&old_password, &user.2)?;
        if !is_valid {
            return Err(AppError::Authentication("Current password is incorrect".to_string()));
        }

        // Check username is not in new password
        if new_password.to_lowercase().contains(&user.1.to_lowercase()) {
            return Err(AppError::Validation { field: "new_password".to_string(), message: "New password must not contain username".to_string() });
        }

        // Update password
        let new_hash = hash_password(&new_password)?;
        let _ = sqlx::query(
            r#"
            UPDATE sys_users
            SET password_hash = $1,
                last_password_changed_at = NOW(),
                password_expires_at = NOW() + INTERVAL '90 days'
            WHERE id = $2
            "#,
        )
        .bind(&new_hash)
        .bind(user_id)
        .execute(db)
        .await
        .map_err(|e| AppError::Internal(Some(format!("Failed to change password: {}", e))))?;

        Ok(())
    }
}
