// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/","name":"首页","icon":"home","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/system","name":"系统管理","icon":"setting","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/system/users","name":"用户管理","icon":"user","parentId":"4","id":"5"},"6":{"path":"/system/roles","name":"角色管理","icon":"shield","parentId":"4","id":"6"},"7":{"path":"/system/departments","name":"部门管理","icon":"cluster","parentId":"4","id":"7"},"8":{"path":"/system/menus","name":"菜单管理","icon":"menu","parentId":"4","id":"8"},"9":{"path":"*","layout":false,"id":"9"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__user__login__index" */'@/pages/user/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__system__users" */'@/pages/system/users.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__system__roles" */'@/pages/system/roles.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__system__departments" */'@/pages/system/departments.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__system__menus" */'@/pages/system/menus.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/ailabuser1/Desktop/gitcode/kao/frontend/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/Users/ailabuser1/Desktop/gitcode/kao/frontend/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
