// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from '/Users/ailabuser1/Desktop/gitcode/kao/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import SettingOutlined from '/Users/ailabuser1/Desktop/gitcode/kao/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import UserOutlined from '/Users/ailabuser1/Desktop/gitcode/kao/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import ClusterOutlined from '/Users/ailabuser1/Desktop/gitcode/kao/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ClusterOutlined';
import MenuOutlined from '/Users/ailabuser1/Desktop/gitcode/kao/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/MenuOutlined';
export default { HomeOutlined, SettingOutlined, UserOutlined, ClusterOutlined, MenuOutlined };
